 const records = [
  {
    ano: "2023",
    mes: "01",
    dia: "01",
    descripcion: "Año Nuevo",
  },
  {
    ano: "2023",
    mes: "01",
    dia: "06",
    descripcion: "Epifanía - Día de los Reyes Magos",
  },
  {
    ano: "2023",
    mes: "03",
    dia: "08",
    descripcion: "Día Internacional de la Mujer",
  },
  {
    ano: "2023",
    mes: "03",
    dia: "19",
    descripcion: "Día del Hombre",
  },
  {
    ano: "2023",
    mes: "03",
    dia: "20",
    descripcion: "Día Internacional de la Felicidad",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "06",
    descripcion: "Jueves Santo",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "07",
    descripcion: "Viernes Santo",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "26",
    descripcion: "Día de la Secretaria",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "30",
    descripcion: "Día de la Niñez",
  },
  {
    ano: "2023",
    mes: "05",
    dia: "01",
    descripcion: "Día Internacional del trabajo",
  },
  {
    ano: "2023",
    mes: "05",
    dia: "14",
    descripcion: "Día de la Madre",
  },
  {
    ano: "2023",
    mes: "05",
    dia: "15",
    descripcion: "Día del Maestro",
  },
  {
    ano: "2023",
    mes: "06",
    dia: "18",
    descripcion: "Día del Padre",
  },
  {
    ano: "2023",
    mes: "07",
    dia: "20",
    descripcion: "Día de la Independencia de Colombia",
  },
  {
    ano: "2023",
    mes: "09",
    dia: "16",
    descripcion: "Día del Amor y la Amistad",
  },
  {
    ano: "2023",
    mes: "09",
    dia: "28",
    descripcion: "Día del Vendedor",
  },
  {
    ano: "2023",
    mes: "10",
    dia: "12",
    descripcion: "Día de la Raza",
  },
  {
    ano: "2023",
    mes: "10",
    dia: "31",
    descripcion: "Fiesta de los Niños (Fiesta de Disfraces)",
  },
  {
    ano: "2023",
    mes: "11",
    dia: "01",
    descripcion: "Día de Todos los Santos",
  },
  {
    ano: "2023",
    mes: "11",
    dia: "25",
    descripcion: "Viernes Negro (Black Friday)",
  },
  {
    ano: "2023",
    mes: "12",
    dia: "16",
    descripcion: "Día del Aguinaldo",
  },
  {
    ano: "2023",
    mes: "12",
    dia: "25",
    descripcion: "Navidad",
  },
  {
    ano: "2023",
    mes: "02",
    dia: "14",
    descripcion: "Día de San valentín",
  },
  {
    ano: "2023",
    mes: "02",
    dia: "22",
    descripcion: "Carnaval de Barranquilla",
  },
  {
    ano: "2023",
    mes: "03",
    dia: "20",
    descripcion: "Día de San José",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "02",
    descripcion: "Domingo de ramos",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "09",
    descripcion: "Domingo de resurrección",
  },
  {
    ano: "2023",
    mes: "04",
    dia: "23",
    descripcion: "Día del idioma",
  },
  {
    ano: "2023",
    mes: "05",
    dia: "22",
    descripcion: "Día de la ascención",
  },
  {
    ano: "2023",
    mes: "06",
    dia: "12",
    descripcion: "Corpus christi",
  },
  {
    ano: "2023",
    mes: "06",
    dia: "19",
    descripcion: "Sagrado corazón",
  },
  {
    ano: "2023",
    mes: "07",
    dia: "03",
    descripcion: "Día de San pedro y San Pablo",
  },
  {
    ano: "2023",
    mes: "07",
    dia: "21",
    descripcion: "Día Internacional del perro",
  },
  {
    ano: "2023",
    mes: "08",
    dia: "07",
    descripcion: "Batalla Boyacá",
  },
  {
    ano: "2023",
    mes: "08",
    dia: "21",
    descripcion: "Asunción de la virgen",
  },
  {
    ano: "2023",
    mes: "11",
    dia: "13",
    descripcion: "Independencia de Cartagena",
  },
  {
    ano: "2023",
    mes: "11",
    dia: "27",
    descripcion: "Cyber Monday",
  },
  {
    ano: "2023",
    mes: "12",
    dia: "08",
    descripcion: "Inmaculada concepción",
  },
  {
    ano: "2023",
    mes: "12",
    dia: "31",
    descripcion: "Año Nuevo",
  },
  {
    ano: "2024",
    mes: "01",
    dia: "01",
    descripcion: "Año nuevo",
  },
  {
    ano: "2024",
    mes: "01",
    dia: "06",
    descripcion: "Día de los Reyes Magos",
  },
  {
    ano: "2024",
    mes: "01",
    dia: "22",
    descripcion: "Año Nuevo Chino",
  },
  {
    ano: "2024",
    mes: "02",
    dia: "04",
    descripcion: "Día mundial contra el cáncer",
  },
  {
    ano: "2024",
    mes: "02",
    dia: "12",
    descripcion: "Super Bowl",
  },
  {
    ano: "2024",
    mes: "02",
    dia: "13",
    descripcion: "Día de los solteros",
  },
  {
    ano: "2024",
    mes: "02",
    dia: "14",
    descripcion: "Día de San valentín",
  },
  {
    ano: "2024",
    mes: "03",
    dia: "08",
    descripcion: "Día Internacional de la mujer",
  },
  {
    ano: "2024",
    mes: "03",
    dia: "15",
    descripcion: "Día mundial del consumidor",
  },
  {
    ano: "2024",
    mes: "03",
    dia: "17",
    descripcion: "Día de San Patricio",
  },
  {
    ano: "2024",
    mes: "03",
    dia: "25",
    descripcion: "Día de San José (Semana Santa)",
  },
  {
    ano: "2024",
    mes: "03",
    dia: "28",
    descripcion: "Jueves Santo (Semana Santa)",
  },
  {
    ano: "2024",
    mes: "03",
    dia: "29",
    descripcion: "Viernes Santo (Semana Santa)",
  },
  {
    ano: "2024",
    mes: "04",
    dia: "07",
    descripcion: "Día mundial de la salud",
  },
  {
    ano: "2024",
    mes: "04",
    dia: "23",
    descripcion: "Día internacional del libro",
  },
  {
    ano: "2024",
    mes: "04",
    dia: "27",
    descripcion: "Día de la niñez",
  },
  {
    ano: "2024",
    mes: "05",
    dia: "01",
    descripcion: "Día del trabajo",
  },
  {
    ano: "2024",
    mes: "05",
    dia: "12",
    descripcion: "Día de la madre",
  },
  {
    ano: "2024",
    mes: "05",
    dia: "13",
    descripcion: "Día de la Ascención",
  },
  {
    ano: "2024",
    mes: "05",
    dia: "17",
    descripcion: "Día del Internet",
  },
  {
    ano: "2024",
    mes: "06",
    dia: "03",
    descripcion: "Corpus Christi",
  },
  {
    ano: "2024",
    mes: "06",
    dia: "05",
    descripcion: "Día mundial del medio ambiente",
  },
  {
    ano: "2024",
    mes: "06",
    dia: "10",
    descripcion: "Día del Sagrado Corazón",
  },
  {
    ano: "2024",
    mes: "06",
    dia: "16",
    descripcion: "Día del Padre",
  },
  {
    ano: "2024",
    mes: "07",
    dia: "01",
    descripcion: "Día de San pedro y San pablo",
  },
  {
    ano: "2024",
    mes: "07",
    dia: "20",
    descripcion: "Día de la independencia de Colombia",
  },
  {
    ano: "2024",
    mes: "07",
    dia: "21",
    descripcion: "Día mundial del perro",
  },
  {
    ano: "2024",
    mes: "07",
    dia: "30",
    descripcion: "Día internacional de la amistad",
  },
  {
    ano: "2024",
    mes: "08",
    dia: "01",
    descripcion: "Día mundial de la alegría",
  },
  {
    ano: "2024",
    mes: "08",
    dia: "07",
    descripcion: "Batalla de Boyacá",
  },
  {
    ano: "2024",
    mes: "08",
    dia: "19",
    descripcion: "Asunción de la Virgen",
  },
  {
    ano: "2024",
    mes: "08",
    dia: "28",
    descripcion: "Día de los abuelos",
  },
  {
    ano: "2024",
    mes: "09",
    dia: "21",
    descripcion: "Día del amor y la amistad",
  },
  {
    ano: "2024",
    mes: "09",
    dia: "27",
    descripcion: "Día mundial del turismo",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "04",
    descripcion: "Día mundial de los animales",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "10",
    descripcion: "Día mundial de la salud mental",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "14",
    descripcion: "Día de la Raza",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "19",
    descripcion: "Día internacional de la lucha contra el cáncer de mama",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "19",
    descripcion: "Hot Sale",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "20",
    descripcion: "Hot Sale",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "21",
    descripcion: "Hot Sale",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "22",
    descripcion: "Hot Sale",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "23",
    descripcion: "Hot Sale",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "31",
    descripcion: "Halloween o Día de las Brujas",
  },
  {
    ano: "2024",
    mes: "11",
    dia: "01",
    descripcion: "Día de todos los santos",
  },
  {
    ano: "2024",
    mes: "11",
    dia: "11",
    descripcion: "Día de la Independencia de Cartagena",
  },
  {
    ano: "2024",
    mes: "11",
    dia: "29",
    descripcion: "Black Friday",
  },
  {
    ano: "2024",
    mes: "12",
    dia: "02",
    descripcion: "Cyberlunes o Cyber Monday",
  },
  {
    ano: "2024",
    mes: "12",
    dia: "08",
    descripcion: "Día de la Inmaculada Concepción",
  },
  {
    ano: "2024",
    mes: "12",
    dia: "16",
    descripcion: "Inicio de la Novena de Navidad",
  },
  {
    ano: "2024",
    mes: "12",
    dia: "24",
    descripcion: "Navidad",
  },
  {
    ano: "2024",
    mes: "12",
    dia: "28",
    descripcion: "Día de los santos Inocentes",
  },
  {
    ano: "2024",
    mes: "12",
    dia: "31",
    descripcion: "Fin de Año",
  },
  {
    ano: "2024",
    mes: "10",
    dia: "21",
    descripcion: "Inicio del OktoberFest",
  },
  {
    ano: "2024",
    mes: "07",
    dia: "14",
    descripcion: "Final Copa America",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "08",
    dia: "15",
    descripcion: "Aniversario 20 Portal del Quindio",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "08",
    dia: "17",
    descripcion: "Evento Serenata Teleantioquia",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "09",
    dia: "10",
    descripcion: "Partido eliminatoria Colombia vs Argentina",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "09",
    dia: "06",
    descripcion: "Partido eliminatoria Perú vs Colombia",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "01",
    dia: "06",
    descripcion: "Feria de Manizales",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "02",
    dia: "10",
    descripcion: "Carnaval de Barranquilla",
    __v: 0,
  },
  {
    ano: "2024",
    mes: "09",
    dia: "27",
    descripcion: "CELEBRACION ANIVERSARIO 20",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "01",
    dia: "01",
    descripcion: "Año nuevo",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "01",
    dia: "06",
    descripcion: "Día de los Reyes Magos",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "03",
    dia: "24",
    descripcion: "Día de San José",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "04",
    dia: "17",
    descripcion: "Jueves Santo",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "04",
    dia: "18",
    descripcion: "Viernes Santo",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "05",
    dia: "01",
    descripcion: "Día del Trabajo",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "06",
    dia: "02",
    descripcion: "Día de la Ascensión",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "06",
    dia: "23",
    descripcion: "Corpus Christi",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "06",
    dia: "30",
    descripcion: "Día de San Pedro y San Pablo",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "07",
    dia: "20",
    descripcion: "Día de la Independencia Colombia",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "08",
    dia: "07",
    descripcion: "Batalla de Boyacá (Independencia de Colombia)",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "08",
    dia: "18",
    descripcion: "Asunción de la Virgen",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "10",
    dia: "13",
    descripcion: "Día de la Raza",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "11",
    dia: "17",
    descripcion: "Día de la Independencia de Cartagena",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "08",
    descripcion: "Día de la Inmaculada Concepción",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "25",
    descripcion: "Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "01",
    dia: "04",
    descripcion: "Feria de manizales",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "03",
    dia: "01",
    descripcion: "Carnaval de Barranquilla",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "02",
    dia: "14",
    descripcion: "Día de San Valentín",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "03",
    dia: "15",
    descripcion: "Día mundial del consumidor",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "03",
    dia: "19",
    descripcion: "Día internacional del hombre",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "05",
    dia: "11",
    descripcion: "Día de la madre",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "08",
    dia: "01",
    descripcion: "Feria de las flores",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "09",
    dia: "21",
    descripcion: "Amor y amistad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "10",
    dia: "31",
    descripcion: "Halloween",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "11",
    dia: "03",
    descripcion: "Día de todos los Santos",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "11",
    dia: "28",
    descripcion: "Black Friday",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "01",
    descripcion: "CyberMonday",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "06",
    dia: "15",
    descripcion: "Dia del Padre",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "07",
    descripcion: "Dia de la velitas",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "16",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "17",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "18",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "19",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "20",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "21",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "22",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "23",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "24",
    descripcion: "Novena Navidad",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "12",
    dia: "28",
    descripcion: "Santos inocentes",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "03",
    dia: "08",
    descripcion: "Día internacional de la mujer",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "04",
    dia: "13",
    descripcion: "Domingo de ramos",
    __v: 0,
  },
  {
    ano: "2025",
    mes: "04",
    dia: "26",
    descripcion: "Día de la Secretaria",
    __v: 0,
  },
];
export default records;